TAXI_COLLECTION = 'taxi'
LOCATION_COLLECTION = 'boundary'
RIDE_DETAILS_COLLECTION = 'ridedetails'
STREAM_COLLECTION = 'taxi_location_stream'
SPECIAL_EVENTS_COLLECTION = 'special_events'
USERS_COLLECTION = 'users'
BOOKING_HISTORY_COLLECTION = 'booking_request_history'
